// <auto-generated />
using System;
using ApplikasiPenilaianMahasiswa.Api.DataModel;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApplikasiPenilaianMahasiswa.Api.Migrations
{
    [DbContext(typeof(MahasiswaDbContext))]
    [Migration("20240208134203_mengubahCreateByMenjadiStringUsername")]
    partial class mengubahCreateByMenjadiStringUsername
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ApplikasiPenilaianMahasiswa.Api.DataModel.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Attempt")
                        .HasColumnType("int");

                    b.Property<string>("Created_by")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("Created_on")
                        .HasColumnType("datetime2");

                    b.Property<long?>("Deleted_by")
                        .HasMaxLength(50)
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("Deleted_on")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasDefaultValue("auriwanyasper@gmail.com");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("Is_delete")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Modified_by")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("Modified_on")
                        .HasColumnType("datetime2");

                    b.Property<string>("Otp")
                        .HasColumnType("char(6)");

                    b.Property<DateTime?>("OtpExpire")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("RoleGroupId")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("RoleGroupId");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("m_accounts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Attempt = 0,
                            Created_by = "admin",
                            Created_on = new DateTime(2024, 2, 8, 20, 42, 2, 701, DateTimeKind.Local).AddTicks(3333),
                            Email = "auriwanyasper@gmail.com",
                            FirstName = "Super",
                            Is_delete = false,
                            LastName = "Admin",
                            Password = "ac9689e2272427085e35b9d3e3e8bed88cb3434828b43b86fc0596cad4c6e270",
                            RoleGroupId = 1,
                            UserName = "admin"
                        },
                        new
                        {
                            Id = 2,
                            Attempt = 0,
                            Created_by = "admin",
                            Created_on = new DateTime(2024, 2, 8, 20, 42, 2, 701, DateTimeKind.Local).AddTicks(3341),
                            Email = "auriwanyasper@gmail.com",
                            FirstName = "dosen",
                            Is_delete = false,
                            LastName = "tes",
                            Password = "c431bffe6c2cf3b69ad2e9cbbe9806835dbced7c97b9d3f946387ee92eb17018",
                            RoleGroupId = 2,
                            UserName = "dosen"
                        });
                });

            modelBuilder.Entity("ApplikasiPenilaianMahasiswa.Api.DataModel.Agama", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Created_by")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("Created_on")
                        .HasColumnType("datetime2");

                    b.Property<long?>("Deleted_by")
                        .HasMaxLength(50)
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("Deleted_on")
                        .HasColumnType("datetime2");

                    b.Property<string>("Deskripsi")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("Is_delete")
                        .HasColumnType("bit");

                    b.Property<string>("Kode_Agama")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Modified_by")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("Modified_on")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("m_agama");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created_by = "admin",
                            Created_on = new DateTime(2024, 2, 8, 20, 42, 2, 701, DateTimeKind.Local).AddTicks(2530),
                            Deskripsi = "Islam",
                            Is_delete = false,
                            Kode_Agama = "AGM-2401-0001"
                        },
                        new
                        {
                            Id = 2,
                            Created_by = "admin",
                            Created_on = new DateTime(2024, 2, 8, 20, 42, 2, 701, DateTimeKind.Local).AddTicks(2538),
                            Deskripsi = "Kristen",
                            Is_delete = false,
                            Kode_Agama = "AGM-2401-0002"
                        },
                        new
                        {
                            Id = 3,
                            Created_by = "admin",
                            Created_on = new DateTime(2024, 2, 8, 20, 42, 2, 701, DateTimeKind.Local).AddTicks(2546),
                            Deskripsi = "Katolik",
                            Is_delete = false,
                            Kode_Agama = "AGM-2401-0003"
                        },
                        new
                        {
                            Id = 4,
                            Created_by = "admin",
                            Created_on = new DateTime(2024, 2, 8, 20, 42, 2, 701, DateTimeKind.Local).AddTicks(2740),
                            Deskripsi = "Hindu",
                            Is_delete = false,
                            Kode_Agama = "AGM-2401-0004"
                        },
                        new
                        {
                            Id = 5,
                            Created_by = "admin",
                            Created_on = new DateTime(2024, 2, 8, 20, 42, 2, 701, DateTimeKind.Local).AddTicks(2750),
                            Deskripsi = "Budha",
                            Is_delete = false,
                            Kode_Agama = "AGM-2401-0005"
                        });
                });

            modelBuilder.Entity("ApplikasiPenilaianMahasiswa.Api.DataModel.AuthorizationGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Created_by")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("Created_on")
                        .HasColumnType("datetime2");

                    b.Property<long?>("Deleted_by")
                        .HasMaxLength(50)
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("Deleted_on")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Is_delete")
                        .HasColumnType("bit");

                    b.Property<string>("Modified_by")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("Modified_on")
                        .HasColumnType("datetime2");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("RoleGroupId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleGroupId");

                    b.ToTable("m_authorization_groups");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created_by = "admin",
                            Created_on = new DateTime(2024, 2, 8, 20, 42, 2, 701, DateTimeKind.Local).AddTicks(3404),
                            Is_delete = false,
                            Role = "jurusan",
                            RoleGroupId = 1
                        },
                        new
                        {
                            Id = 2,
                            Created_by = "admin",
                            Created_on = new DateTime(2024, 2, 8, 20, 42, 2, 701, DateTimeKind.Local).AddTicks(3410),
                            Is_delete = false,
                            Role = "mahasiswa",
                            RoleGroupId = 1
                        },
                        new
                        {
                            Id = 3,
                            Created_by = "admin",
                            Created_on = new DateTime(2024, 2, 8, 20, 42, 2, 701, DateTimeKind.Local).AddTicks(3420),
                            Is_delete = false,
                            Role = "agama",
                            RoleGroupId = 1
                        },
                        new
                        {
                            Id = 4,
                            Created_by = "admin",
                            Created_on = new DateTime(2024, 2, 8, 20, 42, 2, 701, DateTimeKind.Local).AddTicks(3433),
                            Is_delete = false,
                            Role = "dosen",
                            RoleGroupId = 1
                        },
                        new
                        {
                            Id = 5,
                            Created_by = "admin",
                            Created_on = new DateTime(2024, 2, 8, 20, 42, 2, 701, DateTimeKind.Local).AddTicks(3441),
                            Is_delete = false,
                            Role = "nilai",
                            RoleGroupId = 1
                        },
                        new
                        {
                            Id = 6,
                            Created_by = "admin",
                            Created_on = new DateTime(2024, 2, 8, 20, 42, 2, 701, DateTimeKind.Local).AddTicks(3449),
                            Is_delete = false,
                            Role = "typedosen",
                            RoleGroupId = 1
                        },
                        new
                        {
                            Id = 7,
                            Created_by = "admin",
                            Created_on = new DateTime(2024, 2, 8, 20, 42, 2, 701, DateTimeKind.Local).AddTicks(3455),
                            Is_delete = false,
                            Role = "ujian",
                            RoleGroupId = 1
                        });
                });

            modelBuilder.Entity("ApplikasiPenilaianMahasiswa.Api.DataModel.Dosen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Created_by")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("Created_on")
                        .HasColumnType("datetime2");

                    b.Property<long?>("Deleted_by")
                        .HasMaxLength(50)
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("Deleted_on")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id_Jurusan")
                        .HasColumnType("int");

                    b.Property<int>("Id_Type_Dosen")
                        .HasColumnType("int");

                    b.Property<bool>("Is_delete")
                        .HasColumnType("bit");

                    b.Property<string>("Kode_Dosen")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Modified_by")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("Modified_on")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nama_Dosen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Id_Jurusan");

                    b.HasIndex("Id_Type_Dosen");

                    b.ToTable("m_dosen");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created_by = "admin",
                            Created_on = new DateTime(2024, 2, 8, 20, 42, 2, 701, DateTimeKind.Local).AddTicks(3070),
                            Id_Jurusan = 1,
                            Id_Type_Dosen = 2,
                            Is_delete = false,
                            Kode_Dosen = "DSN-2401-0001",
                            Nama_Dosen = "Prof. Dr. Retno Wahyuningsih"
                        },
                        new
                        {
                            Id = 2,
                            Created_by = "admin",
                            Created_on = new DateTime(2024, 2, 8, 20, 42, 2, 701, DateTimeKind.Local).AddTicks(3080),
                            Id_Jurusan = 2,
                            Id_Type_Dosen = 1,
                            Is_delete = false,
                            Kode_Dosen = "DSN-2401-0002",
                            Nama_Dosen = "Prof. Roy M. Sutikno"
                        },
                        new
                        {
                            Id = 3,
                            Created_by = "admin",
                            Created_on = new DateTime(2024, 2, 8, 20, 42, 2, 701, DateTimeKind.Local).AddTicks(3087),
                            Id_Jurusan = 3,
                            Id_Type_Dosen = 2,
                            Is_delete = false,
                            Kode_Dosen = "DSN-2401-0003",
                            Nama_Dosen = "Prof. Hendri A. Verburgh"
                        },
                        new
                        {
                            Id = 4,
                            Created_by = "admin",
                            Created_on = new DateTime(2024, 2, 8, 20, 42, 2, 701, DateTimeKind.Local).AddTicks(3091),
                            Id_Jurusan = 4,
                            Id_Type_Dosen = 2,
                            Is_delete = false,
                            Kode_Dosen = "DSN-2401-0004",
                            Nama_Dosen = "Prof. Risma Suparwata"
                        },
                        new
                        {
                            Id = 5,
                            Created_by = "admin",
                            Created_on = new DateTime(2024, 2, 8, 20, 42, 2, 701, DateTimeKind.Local).AddTicks(3095),
                            Id_Jurusan = 5,
                            Id_Type_Dosen = 1,
                            Is_delete = false,
                            Kode_Dosen = "DSN-2401-0005",
                            Nama_Dosen = "Prof. Amir Sjarifuddin Madjid, MM, MA"
                        });
                });

            modelBuilder.Entity("ApplikasiPenilaianMahasiswa.Api.DataModel.Jurusan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Created_by")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("Created_on")
                        .HasColumnType("datetime2");

                    b.Property<long?>("Deleted_by")
                        .HasMaxLength(50)
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("Deleted_on")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Is_delete")
                        .HasColumnType("bit");

                    b.Property<string>("Kode_Jurusan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Modified_by")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("Modified_on")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nama_Jurusan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status_Jurusan")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("m_jurusan");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created_by = "admin",
                            Created_on = new DateTime(2024, 2, 8, 20, 42, 2, 701, DateTimeKind.Local).AddTicks(1794),
                            Is_delete = false,
                            Kode_Jurusan = "JUR-2401-0001",
                            Nama_Jurusan = "Teknik Informatika",
                            Status_Jurusan = "Aktif"
                        },
                        new
                        {
                            Id = 2,
                            Created_by = "admin",
                            Created_on = new DateTime(2024, 2, 8, 20, 42, 2, 701, DateTimeKind.Local).AddTicks(1856),
                            Is_delete = false,
                            Kode_Jurusan = "JUR-2401-0002",
                            Nama_Jurusan = "Management Informatika",
                            Status_Jurusan = "Aktif"
                        },
                        new
                        {
                            Id = 3,
                            Created_by = "admin",
                            Created_on = new DateTime(2024, 2, 8, 20, 42, 2, 701, DateTimeKind.Local).AddTicks(1860),
                            Is_delete = false,
                            Kode_Jurusan = "JUR-2401-0003",
                            Nama_Jurusan = "Sistem Informasi",
                            Status_Jurusan = "Non Aktif"
                        },
                        new
                        {
                            Id = 4,
                            Created_by = "admin",
                            Created_on = new DateTime(2024, 2, 8, 20, 42, 2, 701, DateTimeKind.Local).AddTicks(1867),
                            Is_delete = false,
                            Kode_Jurusan = "JUR-2401-0004",
                            Nama_Jurusan = "Sistem Komputer",
                            Status_Jurusan = "Aktif"
                        },
                        new
                        {
                            Id = 5,
                            Created_by = "admin",
                            Created_on = new DateTime(2024, 2, 8, 20, 42, 2, 701, DateTimeKind.Local).AddTicks(1871),
                            Is_delete = false,
                            Kode_Jurusan = "JUR-2401-0005",
                            Nama_Jurusan = "Komputer Akuntansi",
                            Status_Jurusan = "Non Aktif"
                        });
                });

            modelBuilder.Entity("ApplikasiPenilaianMahasiswa.Api.DataModel.Mahasiswa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Alamat")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Created_by")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("Created_on")
                        .HasColumnType("datetime2");

                    b.Property<long?>("Deleted_by")
                        .HasMaxLength(50)
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("Deleted_on")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id_Agama")
                        .HasColumnType("int");

                    b.Property<int>("Id_Jurusan")
                        .HasColumnType("int");

                    b.Property<bool>("Is_delete")
                        .HasColumnType("bit");

                    b.Property<string>("Kode_Mahasiswa")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Modified_by")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("Modified_on")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nama_Mahasiswa")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Id_Agama");

                    b.HasIndex("Id_Jurusan");

                    b.ToTable("m_mahasiswa");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Alamat = "Jl. Mawar No 3 RT 05 Cicalengka, Bandung",
                            Created_by = "admin",
                            Created_on = new DateTime(2024, 2, 8, 20, 42, 2, 701, DateTimeKind.Local).AddTicks(2815),
                            Id_Agama = 1,
                            Id_Jurusan = 1,
                            Is_delete = false,
                            Kode_Mahasiswa = "MHS-2401-0001",
                            Nama_Mahasiswa = "Budi Gunawan"
                        },
                        new
                        {
                            Id = 2,
                            Alamat = "Jl. Kebagusan No. 33 RT04 RW06 Bandung",
                            Created_by = "admin",
                            Created_on = new DateTime(2024, 2, 8, 20, 42, 2, 701, DateTimeKind.Local).AddTicks(2825),
                            Id_Agama = 2,
                            Id_Jurusan = 2,
                            Is_delete = false,
                            Kode_Mahasiswa = "MHS-2401-0002",
                            Nama_Mahasiswa = "Rinto Raharjo"
                        },
                        new
                        {
                            Id = 3,
                            Alamat = "Jl. Sumatera No. 12 RT02 RW01, Ciamis",
                            Created_by = "admin",
                            Created_on = new DateTime(2024, 2, 8, 20, 42, 2, 701, DateTimeKind.Local).AddTicks(2830),
                            Id_Agama = 1,
                            Id_Jurusan = 3,
                            Is_delete = false,
                            Kode_Mahasiswa = "MHS-2401-0003",
                            Nama_Mahasiswa = "Asep Saepudin"
                        },
                        new
                        {
                            Id = 4,
                            Alamat = "Jl. Jawa No 01 RT01 RW01, Jakarta Pusat",
                            Created_by = "admin",
                            Created_on = new DateTime(2024, 2, 8, 20, 42, 2, 701, DateTimeKind.Local).AddTicks(2840),
                            Id_Agama = 1,
                            Id_Jurusan = 1,
                            Is_delete = false,
                            Kode_Mahasiswa = "MHS-2401-0004",
                            Nama_Mahasiswa = "M. Hafif Isbullah"
                        },
                        new
                        {
                            Id = 5,
                            Alamat = "Jl. Niagara No. 54 RT01 RW09, Surabaya",
                            Created_by = "admin",
                            Created_on = new DateTime(2024, 2, 8, 20, 42, 2, 701, DateTimeKind.Local).AddTicks(2847),
                            Id_Agama = 3,
                            Id_Jurusan = 2,
                            Is_delete = false,
                            Kode_Mahasiswa = "MHS-2401-0005",
                            Nama_Mahasiswa = "Cahyono"
                        });
                });

            modelBuilder.Entity("ApplikasiPenilaianMahasiswa.Api.DataModel.Nilai", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Created_by")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("Created_on")
                        .HasColumnType("datetime2");

                    b.Property<long?>("Deleted_by")
                        .HasMaxLength(50)
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("Deleted_on")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id_Mahasiswa")
                        .HasColumnType("int");

                    b.Property<int>("Id_Ujian")
                        .HasColumnType("int");

                    b.Property<bool>("Is_delete")
                        .HasColumnType("bit");

                    b.Property<string>("Modified_by")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("Modified_on")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("NilaiMahasiswa")
                        .HasColumnType("decimal(8,2)");

                    b.HasKey("Id");

                    b.HasIndex("Id_Mahasiswa");

                    b.HasIndex("Id_Ujian");

                    b.ToTable("m_nilai");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created_by = "admin",
                            Created_on = new DateTime(2024, 2, 8, 20, 42, 2, 701, DateTimeKind.Local).AddTicks(3169),
                            Id_Mahasiswa = 4,
                            Id_Ujian = 1,
                            Is_delete = false,
                            NilaiMahasiswa = 90m
                        },
                        new
                        {
                            Id = 2,
                            Created_by = "admin",
                            Created_on = new DateTime(2024, 2, 8, 20, 42, 2, 701, DateTimeKind.Local).AddTicks(3177),
                            Id_Mahasiswa = 1,
                            Id_Ujian = 1,
                            Is_delete = false,
                            NilaiMahasiswa = 80m
                        },
                        new
                        {
                            Id = 3,
                            Created_by = "admin",
                            Created_on = new DateTime(2024, 2, 8, 20, 42, 2, 701, DateTimeKind.Local).AddTicks(3191),
                            Id_Mahasiswa = 2,
                            Id_Ujian = 3,
                            Is_delete = false,
                            NilaiMahasiswa = 85m
                        },
                        new
                        {
                            Id = 4,
                            Created_by = "admin",
                            Created_on = new DateTime(2024, 2, 8, 20, 42, 2, 701, DateTimeKind.Local).AddTicks(3198),
                            Id_Mahasiswa = 4,
                            Id_Ujian = 2,
                            Is_delete = false,
                            NilaiMahasiswa = 95m
                        },
                        new
                        {
                            Id = 5,
                            Created_by = "admin",
                            Created_on = new DateTime(2024, 2, 8, 20, 42, 2, 701, DateTimeKind.Local).AddTicks(3203),
                            Id_Mahasiswa = 5,
                            Id_Ujian = 5,
                            Is_delete = false,
                            NilaiMahasiswa = 70m
                        });
                });

            modelBuilder.Entity("ApplikasiPenilaianMahasiswa.Api.DataModel.RoleGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Created_by")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("Created_on")
                        .HasColumnType("datetime2");

                    b.Property<long?>("Deleted_by")
                        .HasMaxLength(50)
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("Deleted_on")
                        .HasColumnType("datetime2");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("Is_delete")
                        .HasColumnType("bit");

                    b.Property<string>("Modified_by")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("Modified_on")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("GroupName")
                        .IsUnique();

                    b.ToTable("m_role_group");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created_by = "admin",
                            Created_on = new DateTime(2024, 2, 8, 20, 42, 2, 701, DateTimeKind.Local).AddTicks(3258),
                            GroupName = "Admin",
                            Is_delete = false
                        },
                        new
                        {
                            Id = 2,
                            Created_by = "admin",
                            Created_on = new DateTime(2024, 2, 8, 20, 42, 2, 701, DateTimeKind.Local).AddTicks(3262),
                            GroupName = "Dosen",
                            Is_delete = false
                        },
                        new
                        {
                            Id = 3,
                            Created_by = "admin",
                            Created_on = new DateTime(2024, 2, 8, 20, 42, 2, 701, DateTimeKind.Local).AddTicks(3267),
                            GroupName = "Mahasiswa",
                            Is_delete = false
                        });
                });

            modelBuilder.Entity("ApplikasiPenilaianMahasiswa.Api.DataModel.TypeDosen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Created_by")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("Created_on")
                        .HasColumnType("datetime2");

                    b.Property<long?>("Deleted_by")
                        .HasMaxLength(50)
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("Deleted_on")
                        .HasColumnType("datetime2");

                    b.Property<string>("Deskripsi")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("Is_delete")
                        .HasColumnType("bit");

                    b.Property<string>("Kode_Type_Dosen")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Modified_by")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("Modified_on")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("m_type_dosen");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created_by = "admin",
                            Created_on = new DateTime(2024, 2, 8, 20, 42, 2, 701, DateTimeKind.Local).AddTicks(3009),
                            Deskripsi = "Tetap",
                            Is_delete = false,
                            Kode_Type_Dosen = "TYP-2401-0001"
                        },
                        new
                        {
                            Id = 2,
                            Created_by = "admin",
                            Created_on = new DateTime(2024, 2, 8, 20, 42, 2, 701, DateTimeKind.Local).AddTicks(3017),
                            Deskripsi = "Honorer",
                            Is_delete = false,
                            Kode_Type_Dosen = "TYP-2401-0002"
                        },
                        new
                        {
                            Id = 3,
                            Created_by = "admin",
                            Created_on = new DateTime(2024, 2, 8, 20, 42, 2, 701, DateTimeKind.Local).AddTicks(3023),
                            Deskripsi = "Expertise",
                            Is_delete = false,
                            Kode_Type_Dosen = "TYP-2401-0003"
                        });
                });

            modelBuilder.Entity("ApplikasiPenilaianMahasiswa.Api.DataModel.Ujian", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Created_by")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("Created_on")
                        .HasColumnType("datetime2");

                    b.Property<long?>("Deleted_by")
                        .HasMaxLength(50)
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("Deleted_on")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Is_delete")
                        .HasColumnType("bit");

                    b.Property<string>("Kode_Ujian")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Modified_by")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("Modified_on")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nama_Ujian")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status_Ujian")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("m_ujian");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created_by = "admin",
                            Created_on = new DateTime(2024, 2, 8, 20, 42, 2, 701, DateTimeKind.Local).AddTicks(2923),
                            Is_delete = false,
                            Kode_Ujian = "UJN-2401-0001",
                            Nama_Ujian = "Algoritma",
                            Status_Ujian = "Aktif"
                        },
                        new
                        {
                            Id = 2,
                            Created_by = "admin",
                            Created_on = new DateTime(2024, 2, 8, 20, 42, 2, 701, DateTimeKind.Local).AddTicks(2929),
                            Is_delete = false,
                            Kode_Ujian = "UJN-2401-0002",
                            Nama_Ujian = "Aljabar",
                            Status_Ujian = "Aktif"
                        },
                        new
                        {
                            Id = 3,
                            Created_by = "admin",
                            Created_on = new DateTime(2024, 2, 8, 20, 42, 2, 701, DateTimeKind.Local).AddTicks(2935),
                            Is_delete = false,
                            Kode_Ujian = "UJN-2401-0003",
                            Nama_Ujian = "Statistika",
                            Status_Ujian = "Non Aktif"
                        },
                        new
                        {
                            Id = 4,
                            Created_by = "admin",
                            Created_on = new DateTime(2024, 2, 8, 20, 42, 2, 701, DateTimeKind.Local).AddTicks(2940),
                            Is_delete = false,
                            Kode_Ujian = "UJN-2401-0004",
                            Nama_Ujian = "Etika Profesi",
                            Status_Ujian = "Non Aktif"
                        },
                        new
                        {
                            Id = 5,
                            Created_by = "admin",
                            Created_on = new DateTime(2024, 2, 8, 20, 42, 2, 701, DateTimeKind.Local).AddTicks(2946),
                            Is_delete = false,
                            Kode_Ujian = "UJN-2401-0005",
                            Nama_Ujian = "Bahasa Inggris",
                            Status_Ujian = "Aktif"
                        });
                });

            modelBuilder.Entity("ApplikasiPenilaianMahasiswa.Api.DataModel.Account", b =>
                {
                    b.HasOne("ApplikasiPenilaianMahasiswa.Api.DataModel.RoleGroup", "RoleGroup")
                        .WithMany()
                        .HasForeignKey("RoleGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RoleGroup");
                });

            modelBuilder.Entity("ApplikasiPenilaianMahasiswa.Api.DataModel.AuthorizationGroup", b =>
                {
                    b.HasOne("ApplikasiPenilaianMahasiswa.Api.DataModel.RoleGroup", "RoleGroup")
                        .WithMany("AuthorizationGroups")
                        .HasForeignKey("RoleGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RoleGroup");
                });

            modelBuilder.Entity("ApplikasiPenilaianMahasiswa.Api.DataModel.Dosen", b =>
                {
                    b.HasOne("ApplikasiPenilaianMahasiswa.Api.DataModel.Jurusan", "Jurusan")
                        .WithMany()
                        .HasForeignKey("Id_Jurusan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApplikasiPenilaianMahasiswa.Api.DataModel.TypeDosen", "TypeDosen")
                        .WithMany()
                        .HasForeignKey("Id_Type_Dosen")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Jurusan");

                    b.Navigation("TypeDosen");
                });

            modelBuilder.Entity("ApplikasiPenilaianMahasiswa.Api.DataModel.Mahasiswa", b =>
                {
                    b.HasOne("ApplikasiPenilaianMahasiswa.Api.DataModel.Agama", "Agama")
                        .WithMany()
                        .HasForeignKey("Id_Agama")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApplikasiPenilaianMahasiswa.Api.DataModel.Jurusan", "Jurusan")
                        .WithMany()
                        .HasForeignKey("Id_Jurusan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agama");

                    b.Navigation("Jurusan");
                });

            modelBuilder.Entity("ApplikasiPenilaianMahasiswa.Api.DataModel.Nilai", b =>
                {
                    b.HasOne("ApplikasiPenilaianMahasiswa.Api.DataModel.Mahasiswa", "Mahasiswa")
                        .WithMany()
                        .HasForeignKey("Id_Mahasiswa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApplikasiPenilaianMahasiswa.Api.DataModel.Ujian", "Ujian")
                        .WithMany()
                        .HasForeignKey("Id_Ujian")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mahasiswa");

                    b.Navigation("Ujian");
                });

            modelBuilder.Entity("ApplikasiPenilaianMahasiswa.Api.DataModel.RoleGroup", b =>
                {
                    b.Navigation("AuthorizationGroups");
                });
#pragma warning restore 612, 618
        }
    }
}
