// <auto-generated />
using System;
using ApplikasiPenilaianMahasiswa.Api.DataModel;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApplikasiPenilaianMahasiswa.Api.Migrations
{
    [DbContext(typeof(MahasiswaDbContext))]
    partial class MahasiswaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ApplikasiPenilaianMahasiswa.Api.DataModel.Agama", b =>
                {
                    b.Property<string>("Kode_Agama")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<long>("Created_by")
                        .HasMaxLength(50)
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Created_on")
                        .HasColumnType("datetime2");

                    b.Property<long?>("Deleted_by")
                        .HasMaxLength(50)
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("Deleted_on")
                        .HasColumnType("datetime2");

                    b.Property<string>("Deskripsi")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Is_delete")
                        .HasColumnType("bit");

                    b.Property<long?>("Modified_by")
                        .HasMaxLength(50)
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("Modified_on")
                        .HasColumnType("datetime2");

                    b.HasKey("Kode_Agama");

                    b.ToTable("m_agama");

                    b.HasData(
                        new
                        {
                            Kode_Agama = "A001",
                            Created_by = 1L,
                            Created_on = new DateTime(2024, 1, 24, 17, 18, 44, 909, DateTimeKind.Local).AddTicks(1294),
                            Deskripsi = "Islam",
                            Id = 1,
                            Is_delete = false
                        },
                        new
                        {
                            Kode_Agama = "A002",
                            Created_by = 1L,
                            Created_on = new DateTime(2024, 1, 24, 17, 18, 44, 909, DateTimeKind.Local).AddTicks(1296),
                            Deskripsi = "Kristen",
                            Id = 2,
                            Is_delete = false
                        },
                        new
                        {
                            Kode_Agama = "A003",
                            Created_by = 1L,
                            Created_on = new DateTime(2024, 1, 24, 17, 18, 44, 909, DateTimeKind.Local).AddTicks(1298),
                            Deskripsi = "Katolik",
                            Id = 4,
                            Is_delete = false
                        },
                        new
                        {
                            Kode_Agama = "A004",
                            Created_by = 1L,
                            Created_on = new DateTime(2024, 1, 24, 17, 18, 44, 909, DateTimeKind.Local).AddTicks(1299),
                            Deskripsi = "Hindu",
                            Id = 4,
                            Is_delete = false
                        },
                        new
                        {
                            Kode_Agama = "A005",
                            Created_by = 1L,
                            Created_on = new DateTime(2024, 1, 24, 17, 18, 44, 909, DateTimeKind.Local).AddTicks(1300),
                            Deskripsi = "Budha",
                            Id = 5,
                            Is_delete = false
                        });
                });

            modelBuilder.Entity("ApplikasiPenilaianMahasiswa.Api.DataModel.Dosen", b =>
                {
                    b.Property<string>("Kode_Dosen")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<long>("Created_by")
                        .HasMaxLength(50)
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Created_on")
                        .HasColumnType("datetime2");

                    b.Property<long?>("Deleted_by")
                        .HasMaxLength(50)
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("Deleted_on")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Is_delete")
                        .HasColumnType("bit");

                    b.Property<string>("Kode_Jurusan")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Kode_Type_Dosen")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<long?>("Modified_by")
                        .HasMaxLength(50)
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("Modified_on")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nama_Dosen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Kode_Dosen");

                    b.HasIndex("Kode_Jurusan");

                    b.HasIndex("Kode_Type_Dosen");

                    b.ToTable("m_dosen");

                    b.HasData(
                        new
                        {
                            Kode_Dosen = "D001",
                            Created_by = 1L,
                            Created_on = new DateTime(2024, 1, 24, 17, 18, 44, 909, DateTimeKind.Local).AddTicks(1405),
                            Id = 1,
                            Is_delete = false,
                            Kode_Jurusan = "J001",
                            Kode_Type_Dosen = "T002",
                            Nama_Dosen = "Prof. Dr. Retno Wahyuningsih"
                        },
                        new
                        {
                            Kode_Dosen = "D002",
                            Created_by = 1L,
                            Created_on = new DateTime(2024, 1, 24, 17, 18, 44, 909, DateTimeKind.Local).AddTicks(1407),
                            Id = 2,
                            Is_delete = false,
                            Kode_Jurusan = "J002",
                            Kode_Type_Dosen = "T001",
                            Nama_Dosen = "Prof. Roy M. Sutikno"
                        },
                        new
                        {
                            Kode_Dosen = "D003",
                            Created_by = 1L,
                            Created_on = new DateTime(2024, 1, 24, 17, 18, 44, 909, DateTimeKind.Local).AddTicks(1416),
                            Id = 3,
                            Is_delete = false,
                            Kode_Jurusan = "J003",
                            Kode_Type_Dosen = "T002",
                            Nama_Dosen = "Prof. Hendri A. Verburgh"
                        },
                        new
                        {
                            Kode_Dosen = "D004",
                            Created_by = 1L,
                            Created_on = new DateTime(2024, 1, 24, 17, 18, 44, 909, DateTimeKind.Local).AddTicks(1418),
                            Id = 4,
                            Is_delete = false,
                            Kode_Jurusan = "J004",
                            Kode_Type_Dosen = "T002",
                            Nama_Dosen = "Prof. Risma Suparwata"
                        },
                        new
                        {
                            Kode_Dosen = "D005",
                            Created_by = 1L,
                            Created_on = new DateTime(2024, 1, 24, 17, 18, 44, 909, DateTimeKind.Local).AddTicks(1419),
                            Id = 5,
                            Is_delete = false,
                            Kode_Jurusan = "J005",
                            Kode_Type_Dosen = "T001",
                            Nama_Dosen = "Prof. Amir Sjarifuddin Madjid, MM, MA"
                        });
                });

            modelBuilder.Entity("ApplikasiPenilaianMahasiswa.Api.DataModel.Jurusan", b =>
                {
                    b.Property<string>("Kode_Jurusan")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<long>("Created_by")
                        .HasMaxLength(50)
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Created_on")
                        .HasColumnType("datetime2");

                    b.Property<long?>("Deleted_by")
                        .HasMaxLength(50)
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("Deleted_on")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Is_delete")
                        .HasColumnType("bit");

                    b.Property<long?>("Modified_by")
                        .HasMaxLength(50)
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("Modified_on")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nama_Jurusan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status_Jurusan")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Kode_Jurusan");

                    b.ToTable("m_jurusan");

                    b.HasData(
                        new
                        {
                            Kode_Jurusan = "J001",
                            Created_by = 1L,
                            Created_on = new DateTime(2024, 1, 24, 17, 18, 44, 909, DateTimeKind.Local).AddTicks(1149),
                            Id = 1,
                            Is_delete = false,
                            Nama_Jurusan = "Teknik Informatika",
                            Status_Jurusan = "Aktif"
                        },
                        new
                        {
                            Kode_Jurusan = "J002",
                            Created_by = 1L,
                            Created_on = new DateTime(2024, 1, 24, 17, 18, 44, 909, DateTimeKind.Local).AddTicks(1161),
                            Id = 2,
                            Is_delete = false,
                            Nama_Jurusan = "Management Informatika",
                            Status_Jurusan = "Aktif"
                        },
                        new
                        {
                            Kode_Jurusan = "J003",
                            Created_by = 1L,
                            Created_on = new DateTime(2024, 1, 24, 17, 18, 44, 909, DateTimeKind.Local).AddTicks(1162),
                            Id = 3,
                            Is_delete = false,
                            Nama_Jurusan = "Sistem Informasi",
                            Status_Jurusan = "Non Aktif"
                        },
                        new
                        {
                            Kode_Jurusan = "J004",
                            Created_by = 1L,
                            Created_on = new DateTime(2024, 1, 24, 17, 18, 44, 909, DateTimeKind.Local).AddTicks(1164),
                            Id = 4,
                            Is_delete = false,
                            Nama_Jurusan = "Sistem Komputer",
                            Status_Jurusan = "Aktif"
                        },
                        new
                        {
                            Kode_Jurusan = "J005",
                            Created_by = 1L,
                            Created_on = new DateTime(2024, 1, 24, 17, 18, 44, 909, DateTimeKind.Local).AddTicks(1165),
                            Id = 5,
                            Is_delete = false,
                            Nama_Jurusan = "Komputer Akuntansi",
                            Status_Jurusan = "Non Aktif"
                        });
                });

            modelBuilder.Entity("ApplikasiPenilaianMahasiswa.Api.DataModel.Mahasiswa", b =>
                {
                    b.Property<string>("Kode_Mahasiswa")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Alamat")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<long>("Created_by")
                        .HasMaxLength(50)
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Created_on")
                        .HasColumnType("datetime2");

                    b.Property<long?>("Deleted_by")
                        .HasMaxLength(50)
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("Deleted_on")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Is_delete")
                        .HasColumnType("bit");

                    b.Property<string>("Kode_Agama")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Kode_Jurusan")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<long?>("Modified_by")
                        .HasMaxLength(50)
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("Modified_on")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nama_Mahasiswa")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Kode_Mahasiswa");

                    b.HasIndex("Kode_Agama");

                    b.HasIndex("Kode_Jurusan");

                    b.ToTable("m_mahasiswa");

                    b.HasData(
                        new
                        {
                            Kode_Mahasiswa = "M001",
                            Alamat = "Jl. Mawar No 3 RT 05 Cicalengka, Bandung",
                            Created_by = 1L,
                            Created_on = new DateTime(2024, 1, 24, 17, 18, 44, 909, DateTimeKind.Local).AddTicks(1325),
                            Id = 1,
                            Is_delete = false,
                            Kode_Agama = "A001",
                            Kode_Jurusan = "J001",
                            Nama_Mahasiswa = "Budi Gunawan"
                        },
                        new
                        {
                            Kode_Mahasiswa = "M002",
                            Alamat = "Jl. Kebagusan No. 33 RT04 RW06 Bandung",
                            Created_by = 1L,
                            Created_on = new DateTime(2024, 1, 24, 17, 18, 44, 909, DateTimeKind.Local).AddTicks(1326),
                            Id = 2,
                            Is_delete = false,
                            Kode_Agama = "A002",
                            Kode_Jurusan = "J002",
                            Nama_Mahasiswa = "Rinto Raharjo"
                        },
                        new
                        {
                            Kode_Mahasiswa = "M003",
                            Alamat = "Jl. Sumatera No. 12 RT02 RW01, Ciamis",
                            Created_by = 1L,
                            Created_on = new DateTime(2024, 1, 24, 17, 18, 44, 909, DateTimeKind.Local).AddTicks(1328),
                            Id = 3,
                            Is_delete = false,
                            Kode_Agama = "A001",
                            Kode_Jurusan = "J003",
                            Nama_Mahasiswa = "Asep Saepudin"
                        },
                        new
                        {
                            Kode_Mahasiswa = "M004",
                            Alamat = "Jl. Jawa No 01 RT01 RW01, Jakarta Pusat",
                            Created_by = 1L,
                            Created_on = new DateTime(2024, 1, 24, 17, 18, 44, 909, DateTimeKind.Local).AddTicks(1329),
                            Id = 4,
                            Is_delete = false,
                            Kode_Agama = "A001",
                            Kode_Jurusan = "J001",
                            Nama_Mahasiswa = "M. Hafif Isbullah"
                        },
                        new
                        {
                            Kode_Mahasiswa = "M005",
                            Alamat = "Jl. Niagara No. 54 RT01 RW09, Surabaya",
                            Created_by = 1L,
                            Created_on = new DateTime(2024, 1, 24, 17, 18, 44, 909, DateTimeKind.Local).AddTicks(1331),
                            Id = 5,
                            Is_delete = false,
                            Kode_Agama = "A003",
                            Kode_Jurusan = "J002",
                            Nama_Mahasiswa = "Cahyono"
                        });
                });

            modelBuilder.Entity("ApplikasiPenilaianMahasiswa.Api.DataModel.Nilai", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<long>("Created_by")
                        .HasMaxLength(50)
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Created_on")
                        .HasColumnType("datetime2");

                    b.Property<long?>("Deleted_by")
                        .HasMaxLength(50)
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("Deleted_on")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Is_delete")
                        .HasColumnType("bit");

                    b.Property<string>("Kode_Mahasiswa")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Kode_Ujian")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<long?>("Modified_by")
                        .HasMaxLength(50)
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("Modified_on")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("NilaiMahasiswa")
                        .HasColumnType("decimal(8,2)");

                    b.HasKey("Id");

                    b.HasIndex("Kode_Mahasiswa");

                    b.HasIndex("Kode_Ujian");

                    b.ToTable("m_nilai");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created_by = 1L,
                            Created_on = new DateTime(2024, 1, 24, 17, 18, 44, 909, DateTimeKind.Local).AddTicks(1444),
                            Is_delete = false,
                            Kode_Mahasiswa = "M004",
                            Kode_Ujian = "U001",
                            NilaiMahasiswa = 90m
                        },
                        new
                        {
                            Id = 2,
                            Created_by = 1L,
                            Created_on = new DateTime(2024, 1, 24, 17, 18, 44, 909, DateTimeKind.Local).AddTicks(1445),
                            Is_delete = false,
                            Kode_Mahasiswa = "M001",
                            Kode_Ujian = "U001",
                            NilaiMahasiswa = 80m
                        },
                        new
                        {
                            Id = 3,
                            Created_by = 1L,
                            Created_on = new DateTime(2024, 1, 24, 17, 18, 44, 909, DateTimeKind.Local).AddTicks(1447),
                            Is_delete = false,
                            Kode_Mahasiswa = "M002",
                            Kode_Ujian = "U003",
                            NilaiMahasiswa = 85m
                        },
                        new
                        {
                            Id = 4,
                            Created_by = 1L,
                            Created_on = new DateTime(2024, 1, 24, 17, 18, 44, 909, DateTimeKind.Local).AddTicks(1448),
                            Is_delete = false,
                            Kode_Mahasiswa = "M004",
                            Kode_Ujian = "U002",
                            NilaiMahasiswa = 95m
                        },
                        new
                        {
                            Id = 5,
                            Created_by = 1L,
                            Created_on = new DateTime(2024, 1, 24, 17, 18, 44, 909, DateTimeKind.Local).AddTicks(1449),
                            Is_delete = false,
                            Kode_Mahasiswa = "M005",
                            Kode_Ujian = "U005",
                            NilaiMahasiswa = 70m
                        });
                });

            modelBuilder.Entity("ApplikasiPenilaianMahasiswa.Api.DataModel.TypeDosen", b =>
                {
                    b.Property<string>("Kode_Type_Dosen")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<long>("Created_by")
                        .HasMaxLength(50)
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Created_on")
                        .HasColumnType("datetime2");

                    b.Property<long?>("Deleted_by")
                        .HasMaxLength(50)
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("Deleted_on")
                        .HasColumnType("datetime2");

                    b.Property<string>("Deskripsi")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Is_delete")
                        .HasColumnType("bit");

                    b.Property<long?>("Modified_by")
                        .HasMaxLength(50)
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("Modified_on")
                        .HasColumnType("datetime2");

                    b.HasKey("Kode_Type_Dosen");

                    b.ToTable("m_type_dosen");

                    b.HasData(
                        new
                        {
                            Kode_Type_Dosen = "T001",
                            Created_by = 1L,
                            Created_on = new DateTime(2024, 1, 24, 17, 18, 44, 909, DateTimeKind.Local).AddTicks(1384),
                            Deskripsi = "Tetap",
                            Id = 1,
                            Is_delete = false
                        },
                        new
                        {
                            Kode_Type_Dosen = "T002",
                            Created_by = 1L,
                            Created_on = new DateTime(2024, 1, 24, 17, 18, 44, 909, DateTimeKind.Local).AddTicks(1386),
                            Deskripsi = "Honorer",
                            Id = 2,
                            Is_delete = false
                        },
                        new
                        {
                            Kode_Type_Dosen = "T003",
                            Created_by = 1L,
                            Created_on = new DateTime(2024, 1, 24, 17, 18, 44, 909, DateTimeKind.Local).AddTicks(1388),
                            Deskripsi = "Expertise",
                            Id = 3,
                            Is_delete = false
                        });
                });

            modelBuilder.Entity("ApplikasiPenilaianMahasiswa.Api.DataModel.Ujian", b =>
                {
                    b.Property<string>("Kode_Ujian")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<long>("Created_by")
                        .HasMaxLength(50)
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Created_on")
                        .HasColumnType("datetime2");

                    b.Property<long?>("Deleted_by")
                        .HasMaxLength(50)
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("Deleted_on")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Is_delete")
                        .HasColumnType("bit");

                    b.Property<long?>("Modified_by")
                        .HasMaxLength(50)
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("Modified_on")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nama_Ujian")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status_Ujian")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Kode_Ujian");

                    b.ToTable("m_ujian");

                    b.HasData(
                        new
                        {
                            Kode_Ujian = "U001",
                            Created_by = 1L,
                            Created_on = new DateTime(2024, 1, 24, 17, 18, 44, 909, DateTimeKind.Local).AddTicks(1353),
                            Id = 1,
                            Is_delete = false,
                            Nama_Ujian = "Algoritma",
                            Status_Ujian = "Aktif"
                        },
                        new
                        {
                            Kode_Ujian = "U002",
                            Created_by = 1L,
                            Created_on = new DateTime(2024, 1, 24, 17, 18, 44, 909, DateTimeKind.Local).AddTicks(1354),
                            Id = 2,
                            Is_delete = false,
                            Nama_Ujian = "Aljabar",
                            Status_Ujian = "Aktif"
                        },
                        new
                        {
                            Kode_Ujian = "U003",
                            Created_by = 1L,
                            Created_on = new DateTime(2024, 1, 24, 17, 18, 44, 909, DateTimeKind.Local).AddTicks(1355),
                            Id = 3,
                            Is_delete = false,
                            Nama_Ujian = "Statistika",
                            Status_Ujian = "Non Aktif"
                        },
                        new
                        {
                            Kode_Ujian = "U004",
                            Created_by = 1L,
                            Created_on = new DateTime(2024, 1, 24, 17, 18, 44, 909, DateTimeKind.Local).AddTicks(1357),
                            Id = 4,
                            Is_delete = false,
                            Nama_Ujian = "Etika Profesi",
                            Status_Ujian = "Non Aktif"
                        },
                        new
                        {
                            Kode_Ujian = "U005",
                            Created_by = 1L,
                            Created_on = new DateTime(2024, 1, 24, 17, 18, 44, 909, DateTimeKind.Local).AddTicks(1358),
                            Id = 5,
                            Is_delete = false,
                            Nama_Ujian = "Bahasa Inggris",
                            Status_Ujian = "Aktif"
                        });
                });

            modelBuilder.Entity("ApplikasiPenilaianMahasiswa.Api.DataModel.Dosen", b =>
                {
                    b.HasOne("ApplikasiPenilaianMahasiswa.Api.DataModel.Jurusan", "Jurusan")
                        .WithMany()
                        .HasForeignKey("Kode_Jurusan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApplikasiPenilaianMahasiswa.Api.DataModel.TypeDosen", "TypeDosen")
                        .WithMany()
                        .HasForeignKey("Kode_Type_Dosen")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Jurusan");

                    b.Navigation("TypeDosen");
                });

            modelBuilder.Entity("ApplikasiPenilaianMahasiswa.Api.DataModel.Mahasiswa", b =>
                {
                    b.HasOne("ApplikasiPenilaianMahasiswa.Api.DataModel.Agama", "Agama")
                        .WithMany()
                        .HasForeignKey("Kode_Agama")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApplikasiPenilaianMahasiswa.Api.DataModel.Jurusan", "Jurusan")
                        .WithMany()
                        .HasForeignKey("Kode_Jurusan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agama");

                    b.Navigation("Jurusan");
                });

            modelBuilder.Entity("ApplikasiPenilaianMahasiswa.Api.DataModel.Nilai", b =>
                {
                    b.HasOne("ApplikasiPenilaianMahasiswa.Api.DataModel.Mahasiswa", "Mahasiswa")
                        .WithMany()
                        .HasForeignKey("Kode_Mahasiswa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApplikasiPenilaianMahasiswa.Api.DataModel.Ujian", "Ujian")
                        .WithMany()
                        .HasForeignKey("Kode_Ujian")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mahasiswa");

                    b.Navigation("Ujian");
                });
#pragma warning restore 612, 618
        }
    }
}
